server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Moein;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: myjava123

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
